version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: spring_bookshelf
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# docker-compose up -d